@host = https://localhost
@port = 44397

@Restaurants.API_HostAddress = https://localhost:44397


GET {{Restaurants.API_HostAddress}}/api/restaurants

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/1

###

POST {{Restaurants.API_HostAddress}}/api/restaurants
Content-Type: application/json

{
  "Name": "Tasty Tests another",
  "Description": "A cozy restaurant serving a variety of delicious dishes",
  "Category": "Indian",
  "HasDelivery": true,
  "ContactEmail": "info@test.com",
  "ContactNumber": "555-1234",
  "City": "New York",
  "Street": "123 Main Street",
  "PostalCode": "10-010"
}

###

POST {{Restaurants.API_HostAddress}}/api/restaurants
Content-Type: application/json

{
  //CreateRestaurantCommand
}

###

GET {{Restaurants.API_HostAddress}}/api/restaurants

###

PATCH {{Restaurants.API_HostAddress}}/api/restaurants/4
Content-Type: application/json

{
  "Name": "Sample Patch",
  "Description": "A cozy restaurant serving a variety of delicious dishes",
  "HasDelivery": true
}

###

PATCH {{Restaurants.API_HostAddress}}/api/restaurants/9
Content-Type: application/json

{
 
}

###
