@host = https://localhost
@port = 44397

@Restaurants.API_HostAddress = https://localhost:44397


GET {{Restaurants.API_HostAddress}}/api/restaurants

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/1

###
